name: dalle
channels:
    - pytorch
    - huggingface
    - conda-forge
    - defaults
dependencies:
    - python>=3.8
    - pip>22
    - pytorch==1.8.0
    - torchvision>=0.8.2
    - pip:
        - pyflakes>=2.2.0
        - tqdm>=4.46.0
        - pytorch-lightning>=1.5
        - einops
        - omegaconf
        - tokenizers
        - git+https://github.com/openai/CLIP.git
